### ISSUE TITLE
new future/ change custom charset

### ISSUE THREAD

**Issue by shikulja** [CodeheadUK/CBFG#1]
This tool is very easy to use, and I found no similar programs, especially convenient to change the font of letters in the old games, for them, it fits perfectly, only found one problem in the games characters and the characters in the font are in a different order. Can you add the ability to create a font with manual selection of the letters for the font.

I need such a building:
. 0123456789 + - = *% ABCDEFGHIJKLMNOPQRSTUVWXYZ & !? " 'abcdefghijklmnopqrstuvwxyz:, /
АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя

It would be another opportunity to add a shadow for the letters, colors and shadows.
For example how many pixels is the width of the shade, and in what direction (eg down and to the right)

Should I wait for program updates, and when?
(Very necessary for the translation of several games, manually align the letters in photoshop is very long and hard to change later)

**Comment by CodeheadUK** [comment]
Hey Shikulja,

Thanks for the feedback. Unicode characters are one of the stumbling blocks of bitmap fonts. It's hard to cover all the possible glyphs without creating a huge texture.

Your idea is a good one, the ability to preselect a sequence would help limit the texture size, but I'm not sure how the code would select the right sub-texture without a lookup table or some fundamental change to the way the BFF format works.

I certainly don't have time to implement this request, but the code is all here if anyone else feels like taking a stab at it.

**Comment by shikulja** [comment]
it is only needed for image format, not special.

and I will give a hint can be useful
the game was coded ANSI 1252 and 1251 needed a Russian symbols displayed characters, as by the codes were not the Glaive. So I manually rearranged Glaive on the codes in place in 1251 where they were Glaive 1252. It eliminated the characters, and the characters began to appear Russian.

For example, if it were possible to choose the external .ttf files in CBFG, and write a simple program to replace the Glaive in different encodings

**Comment by CodeheadUK** [comment]
Closing. Not possible in current version.
