### ISSUE TITLE
Font height not saved

### ISSUE THREAD

**Issue by Botondar** [CodeheadUK/CBFG#3]
I don't think the .bff files contain the font height that the bitmap was rendered with. I am unsure of how to get this data, where the cell is (much) taller than the character in it.

Other than that, this tool is very useful and easy to use.

**Comment by CodeheadUK** [comment]
Hi Botondar,

You are correct, the individual glyph heights are not stored. This is by design as the glyph height is mostly irrelevant. The cell height provides enough information to render multiple lines of text with constant spacing.
