### ISSUE TITLE
Tag stable release

### ISSUE THREAD

**Issue by akien-mga** [CodeheadUK/CBFG#4]
Hi, thanks for open sourcing CBFG! :)

The website mentions that the version in this repo is v1.45, could you tag the corresponding commit (`git checkout $commit_hash && git tag 1.45 && git push --tags`)?

*Edit:* The downloaded version ("Files only zip") claims it is v1.43 though.

**Comment by CodeheadUK** [comment]
Hi There. Finally got around to updating this. Tags applied (I think, its showing 1.45 as 26 Jun, but I guess there are no real changes, so the date will stay at the last release.)

The 'Files Only Zip' will be at 1.43 , the only difference is some of the update check code got chopped for the GitHub version.
