### ISSUE TITLE
Signed Distance Field Fonts

### ISSUE THREAD

**Issue by h1cks** [CodeheadUK/CBFG#5]
Hi, Mentioned in suggestions, but will raise here.  I have read through the code a fair bit and seems I could add something in relation to creating SDF fonts.   If I find the time, I will pull the code and try and add the feature.  

Also would like:

- Confirm that you can not reload a BFF font file once exported as some information is missing such as font selected.  I may be wrong on this,  If is it true, would you be averse to adding in more information to the file to allow it to be loaded back in.  I need to dig through your code more anyway.

**Comment by CodeheadUK** [comment]
Reloading fonts is something that would be nice. However, the TT font is used to generate the bitmap data in CBFG after each change to the visuals, but only the bitmap data and sizing/spacing metadata is saved into the file. 
There is no guarantee that the original TT font will be present on any given machine if a font was reloaded into CBFG. I guess a larger 'project file' type save could include the TT font with all the CBFG data, but that seems like overkill.

**Comment by CodeheadUK** [comment]
Closing. Not implementable.
