### ISSUE TITLE
Can I write a cross-platform version?

### ISSUE THREAD

**Issue by andrey-moura** [CodeheadUK/CBFG#6]
Hi, I'm re-writing the GUI using a cross-platform framework (wxWidgets). Since you are not updating the repository, can I be a contributor?

**Comment by CodeheadUK** [comment]
Hey. Thanks for your interest. I have started a couple of re-writes of CBFG over the last few years. It would be great to have a updated and cross platform version, but I never seem to find a combination of language and GUI framework that give me everything I need.

I'd be happy to take pull requests if you have a completed feature improvement, or you can fork the project and work on a complete re-write if that's where you're looking to go. 

The codebase as it stands is tied to an old version of Visual Studio and many of the constants aren't recognised by the latest versions. I'd be interested in seeing if the code can be decoupled from Visual Studio, but this version is kinda set in stone now. Any major improvements or changes should probably be made in a new version.

Does that answer your question?
